export const scienceCategories = [
  'the periodic table of elements',
  'particle physics',
  'geometry',
  'optics',
  'geology',
  'neuroscience',
  'palaeontology',
  'zoology',
  'electricity & magnetism',
  'black holes',
  'cryptology',
  'oceanography',
  'botany',
  'logic',
  'linguistics',
  'inorganic chemistry',
  'limbs',
  'trigonometry',
  'anthropology',
  'thermodynamics'
];

export const entertainmentCategories = [
  'harry potter',
  'tarantino films',
  'shrek',
  'nintendo',
  'the matrix',
  'avatar: the last airbender',
  'middle earth',
  'name the actor',
  'board games',
  'classic rock',
  'pirates of the caribbean',
  'the incredibles',
  'a song of ice and fire',
  'mulan',
  'sketch comedy',
  'spider-man',
  'zombies',
  'bethesda games',
  'musical theatre',
  'dragons'
];

export const historyGeographyCategories = [
  'geography by continent',
  'south and central america',
  'british history',
  'africa',
  'the american civil war',
  'the dawn of civilization',
  'islands',
  'bodies of water',
  'the cold war',
  'eastern europe',
  'explorers',
  'canada',
  'the pacific ocean',
  'india',
  'the roman empire',
  'colonial usa',
  'the civil rights movement',
  'the middle east',
  'germany',
  'antarctica',
  'native american peoples',
  'empires'
];

export const foodDrinkCategories = [
  'spices',
  'food and beverage brands',
  'deep fried food',
  'sauce',
  'hors d\'oeuvres',
  'whisk(e)y',
  'chocolate',
  'sausages',
  'tea',
  'wine',
  'sandwiches',
  'breakfast',
  'beans',
  'vodka',
  'east asian food',
  'liqueurs',
  'dessert',
  'steak'
];

export const randomCategories = [
  'things millennials killed',
  'supercars',
  'orange',
  'orthography',
  'romantic composers',
  'the end of the world',
  'monsters',
  'strongman',
  'ships and boats',
  'age restrictions',
  'medieval weaponry',
  'winter sports',
  'memeology',
  'egyptian mythology',
  'hallucinogens',
  'the olympics',
  'percussion',
  'musical instruments',
  'meme platforms',
  'hell'
];
